name: Verify PR

on:
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --pure-lockfile
      - run: mkdir tmp && tar --use-compress-program zstd -cf tmp/project.tar.gz --exclude=./tmp .
      - uses: actions/upload-artifact@v2
        with:
          name: project
          path: tmp/project.tar.gz
          retention-days: 1

  lint:
    name: Verify / Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with: { name: project }
      - run: tar --use-compress-program zstd -xf project.tar.gz
      - run: yarn lint

  test:
    name: Verify / Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with: { name: project }
      - run: tar --use-compress-program zstd -xf project.tar.gz
      - run: yarn test

  build:
    name: Verify / Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with: { name: project }
      - run: tar --use-compress-program zstd -xf project.tar.gz
      - run: yarn build
