name: Verify PR

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Verify / Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --pure-lockfile
      - run: yarn lint

  test:
    name: Verify / Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --pure-lockfile
      - run: yarn test

  build:
    name: Verify / Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn install --pure-lockfile
      - run: yarn build
